#!/usr/bin/env python3
# Copyright 2026 The Sokatoa Project Authors
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        https://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

"""Build gfxr-sqlite end-to-end.

This is the top-level standalone build entry point: it ensures the gfxreconstruct
dependency is built (via build_dependencies.py), then configures and builds the
gfxr-sqlite CMake project, producing the gfxr-sqlite CLI executable, the
gfxr-db-library static library, and the gfxr-db-test test executable.

Typical usage:

    python3 scripts/build.py                # release
    python3 scripts/build.py debug          # debug
    python3 scripts/build.py --clean        # clean rebuild
    python3 scripts/build.py --skip-deps    # skip rebuilding gfxreconstruct
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# Allow importing build_dependencies as a module.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_dependencies  # noqa: E402

PROJECT_ROOT = build_dependencies.PROJECT_ROOT
BUILD_TYPE_RELEASE = build_dependencies.BUILD_TYPE_RELEASE
BUILD_TYPE_DEBUG = build_dependencies.BUILD_TYPE_DEBUG


def verify_dependencies_built(build_type: str) -> None:
    """Fail early with guidance if gfxreconstruct hasn't been built for build_type.

    gfxr-sqlite's CMakeLists.txt includes and links gfxreconstruct's per-config
    output directory ('build' for release, 'dbuild' for debug). If that build was
    not run for the configuration being built, CMake configure/compile later fails
    with a confusing missing-header error (e.g. project_version_<Config>.h). Catch
    the mismatch here with an actionable message instead.
    """
    cmake_config = 'Release' if build_type == BUILD_TYPE_RELEASE else 'Debug'
    output_dir = build_dependencies.gfxreconstruct_cmake_output_dir(build_type)
    # project_version_<Config>.h is generated by gfxreconstruct's CMake into this
    # directory; its presence is a reliable signal the dependency was built here.
    version_header = output_dir.joinpath(f'project_version_{cmake_config}.h')
    if not version_header.is_file():
        raise SystemExit(
            f'\nERROR: gfxreconstruct has not been built for the "{build_type}" configuration.\n'
            f'       Expected build output at:\n'
            f'           {output_dir}\n\n'
            f'       Build the dependency for this configuration first:\n'
            f'           python3 scripts/build_dependencies.py {build_type}\n\n'
            f'       (Or re-run this script without --skip-deps to build it automatically:\n'
            f'           python3 scripts/build.py {build_type})\n')


def build_gfxr_sqlite(build_type: str, clean: bool, parallel: int) -> Path:
    """Configure and build the gfxr-sqlite CMake project. Returns the build dir.

    parallel: number of compilation jobs (0 = use all available cores).
    """
    if build_type == BUILD_TYPE_RELEASE:
        cmake_config = 'Release'
        build_subdir = 'build'
    else:
        cmake_config = 'Debug'
        build_subdir = 'dbuild'

    build_dir = PROJECT_ROOT.joinpath('out', build_subdir)
    if clean and build_dir.exists():
        print(f'Cleaning {build_dir}')
        shutil.rmtree(build_dir)
    build_dir.mkdir(parents=True, exist_ok=True)

    build_dependencies.run(
        ['cmake', '-S', str(PROJECT_ROOT), '-B', str(build_dir),
         f'-DCMAKE_BUILD_TYPE={cmake_config}'])

    # cmake's --parallel with no value uses all cores; with a value uses that many.
    cmake_build = ['cmake', '--build', str(build_dir), '--config', cmake_config]
    if parallel == 0:
        cmake_build += ['--parallel']
    else:
        cmake_build += ['--parallel', str(parallel)]
    build_dependencies.run(cmake_build)
    return build_dir


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('build_type', choices=[BUILD_TYPE_RELEASE, BUILD_TYPE_DEBUG],
                        nargs='?', default=BUILD_TYPE_RELEASE,
                        help='Build configuration (default: release)')
    parser.add_argument('--clean', action='store_true',
                        help='Clean before building (both deps and gfxr-sqlite)')
    parser.add_argument('--skip-deps', action='store_true',
                        help='Skip the dependency build (assume gfxreconstruct is already built)')
    build_dependencies.add_parallel_arg(parser)
    args = parser.parse_args()

    if not args.skip_deps:
        build_dependencies.ensure_gfxreconstruct_initialized()
        build_dependencies.build_gfxreconstruct(args.build_type, args.clean, args.parallel)

    # Guard against a config mismatch (e.g. --skip-deps with deps built for the
    # other configuration) before CMake fails later with an opaque error.
    verify_dependencies_built(args.build_type)

    build_dir = build_gfxr_sqlite(args.build_type, args.clean, args.parallel)
    print(f'\nBuild complete. Artifacts in {build_dir}')


if __name__ == '__main__':
    main()
